
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-3
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-StatsService","number":21,"title":"Add Average Cow Health Service and test","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/21"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-Workflow","number":19,"title":"Trivial changes to optimize the workflow","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/19"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-RemoveMessage","number":17,"title":"Removed toast message when purchasing cows","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/17"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-StatsDb","number":16,"title":"Create database table for commonStats","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/16"}]
