
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-3
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-3
pull_requests: [{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":"Edwin-Yee"},"headRefName":"ey-milk-on-demand-branch","number":53,"title":"Add option to milk an individual commons on demand (in progress)","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/53"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":"Edwin-Yee"},"headRefName":"ey-new-add-modal","number":51,"title":"Added a modal popup when a user tries to delete a commons ","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/51"},{"author":{"id":"U_kgDOBZIIbQ","is_bot":false,"login":"clin947","name":"Xingye Lin"},"headRefName":"Cindy-BackButton","number":49,"title":"add leaderboard back button","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/49"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-HappierCows-UpdateCowHealthEq","number":48,"title":"update cow health equation using effective capacity instead of carrying capacity","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/48"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"hanabicel","name":"Andrew"},"headRefName":"Andrew-CapacityFrontend","number":47,"title":"[Andrew] Add capacityPerUser to Create + Edit pages","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/47"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-HappierCows-EffectiveCapacity","number":44,"title":"Added Effective Capacity Field which is set and returned in every GET endpoint","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/44"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":"Edwin-Yee"},"headRefName":"ey-add-caution-delete-commons","number":30,"title":"Added a modal popup when the users tries to delete a commons. ","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/30"}]
