
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-3
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-HappierCows-PUT","number":40,"title":"Ryan happier cows put","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/40"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-CommonStatsFE","number":39,"title":"Common stats front end","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/39"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-HappierCows-POST","number":38,"title":"rh - edited POST operation and corresponding test cases for capacityPerUser field","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/38"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":"Edwin-Yee"},"headRefName":"ey-add-caution-delete-commons","number":30,"title":"Added a modal popup when the users tries to delete a commons. ","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/pull/30"}]
